ifndef SOSOBUILD
COMMON = .
endif

project.subdirs := \
	base \
	text \
	system \
	log \
	crypto \
	collection \
	config \
	netframe \
	distribute_lock \
	rpc \
	encoding \
	web \
	algorithm \
	compress \
	file \
	net

include $(COMMON)/builder/Generic.mak
