/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "scheduler_types.h"

#include <algorithm>



int _kTaskStateValues[] = {
  TaskState::TASK_WAITING,
  TaskState::TASK_RUNNING,
  TaskState::TASK_TERMINATED
};
const char* _kTaskStateNames[] = {
  "TASK_WAITING",
  "TASK_RUNNING",
  "TASK_TERMINATED"
};
const std::map<int, const char*> _TaskState_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kTaskStateValues, _kTaskStateNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));


