/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef scheduler_TYPES_H
#define scheduler_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>





struct TaskState {
  enum type {
    TASK_WAITING = 0,
    TASK_RUNNING = 1,
    TASK_TERMINATED = 2
  };
};

extern const std::map<int, const char*> _TaskState_VALUES_TO_NAMES;



#endif
