// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recordio_test.proto

#ifndef PROTOBUF_recordio_5ftest_2eproto__INCLUDED
#define PROTOBUF_recordio_5ftest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace common {
namespace file {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_recordio_5ftest_2eproto();
void protobuf_AssignDesc_recordio_5ftest_2eproto();
void protobuf_ShutdownFile_recordio_5ftest_2eproto();

class Record;

// ===================================================================

class Record : public ::google::protobuf::Message {
 public:
  Record();
  virtual ~Record();
  
  Record(const Record& from);
  
  inline Record& operator=(const Record& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Record& default_instance();
  
  void Swap(Record* other);
  
  // implements Message ----------------------------------------------
  
  Record* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Record& from);
  void MergeFrom(const Record& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 int_value = 1;
  inline bool has_int_value() const;
  inline void clear_int_value();
  static const int kIntValueFieldNumber = 1;
  inline ::google::protobuf::uint32 int_value() const;
  inline void set_int_value(::google::protobuf::uint32 value);
  
  // required double double_value = 2;
  inline bool has_double_value() const;
  inline void clear_double_value();
  static const int kDoubleValueFieldNumber = 2;
  inline double double_value() const;
  inline void set_double_value(double value);
  
  // optional string string_value = 3;
  inline bool has_string_value() const;
  inline void clear_string_value();
  static const int kStringValueFieldNumber = 3;
  inline const ::std::string& string_value() const;
  inline void set_string_value(const ::std::string& value);
  inline void set_string_value(const char* value);
  inline void set_string_value(const char* value, size_t size);
  inline ::std::string* mutable_string_value();
  
  // @@protoc_insertion_point(class_scope:common.file.Record)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 int_value_;
  double double_value_;
  ::std::string* string_value_;
  static const ::std::string _default_string_value_;
  friend void  protobuf_AddDesc_recordio_5ftest_2eproto();
  friend void protobuf_AssignDesc_recordio_5ftest_2eproto();
  friend void protobuf_ShutdownFile_recordio_5ftest_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Record* default_instance_;
};
// ===================================================================


// ===================================================================

// Record

// required uint32 int_value = 1;
inline bool Record::has_int_value() const {
  return _has_bit(0);
}
inline void Record::clear_int_value() {
  int_value_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 Record::int_value() const {
  return int_value_;
}
inline void Record::set_int_value(::google::protobuf::uint32 value) {
  _set_bit(0);
  int_value_ = value;
}

// required double double_value = 2;
inline bool Record::has_double_value() const {
  return _has_bit(1);
}
inline void Record::clear_double_value() {
  double_value_ = 0;
  _clear_bit(1);
}
inline double Record::double_value() const {
  return double_value_;
}
inline void Record::set_double_value(double value) {
  _set_bit(1);
  double_value_ = value;
}

// optional string string_value = 3;
inline bool Record::has_string_value() const {
  return _has_bit(2);
}
inline void Record::clear_string_value() {
  if (string_value_ != &_default_string_value_) {
    string_value_->clear();
  }
  _clear_bit(2);
}
inline const ::std::string& Record::string_value() const {
  return *string_value_;
}
inline void Record::set_string_value(const ::std::string& value) {
  _set_bit(2);
  if (string_value_ == &_default_string_value_) {
    string_value_ = new ::std::string;
  }
  string_value_->assign(value);
}
inline void Record::set_string_value(const char* value) {
  _set_bit(2);
  if (string_value_ == &_default_string_value_) {
    string_value_ = new ::std::string;
  }
  string_value_->assign(value);
}
inline void Record::set_string_value(const char* value, size_t size) {
  _set_bit(2);
  if (string_value_ == &_default_string_value_) {
    string_value_ = new ::std::string;
  }
  string_value_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Record::mutable_string_value() {
  _set_bit(2);
  if (string_value_ == &_default_string_value_) {
    string_value_ = new ::std::string;
  }
  return string_value_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace file
}  // namespace common

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_recordio_5ftest_2eproto__INCLUDED
