/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Collector_H
#define Collector_H

#include <thrift/TDispatchProcessor.h>
#include "collector_types.h"



class CollectorIf {
 public:
  virtual ~CollectorIf() {}
  virtual void SendHeartbeat(const std::string& heartbeat_ad) = 0;
  virtual int32_t RegistMachine(const std::string& machine_ad) = 0;
  virtual void MatchMachine(std::string& _return, const std::string& job_ad) = 0;
  virtual void QueryMachine(std::string& _return, const std::string& machine) = 0;
  virtual void ListAllMachines(std::vector<std::string> & _return) = 0;
};

class CollectorIfFactory {
 public:
  typedef CollectorIf Handler;

  virtual ~CollectorIfFactory() {}

  virtual CollectorIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(CollectorIf* /* handler */) = 0;
};

class CollectorIfSingletonFactory : virtual public CollectorIfFactory {
 public:
  CollectorIfSingletonFactory(const boost::shared_ptr<CollectorIf>& iface) : iface_(iface) {}
  virtual ~CollectorIfSingletonFactory() {}

  virtual CollectorIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(CollectorIf* /* handler */) {}

 protected:
  boost::shared_ptr<CollectorIf> iface_;
};

class CollectorNull : virtual public CollectorIf {
 public:
  virtual ~CollectorNull() {}
  void SendHeartbeat(const std::string& /* heartbeat_ad */) {
    return;
  }
  int32_t RegistMachine(const std::string& /* machine_ad */) {
    int32_t _return = 0;
    return _return;
  }
  void MatchMachine(std::string& /* _return */, const std::string& /* job_ad */) {
    return;
  }
  void QueryMachine(std::string& /* _return */, const std::string& /* machine */) {
    return;
  }
  void ListAllMachines(std::vector<std::string> & /* _return */) {
    return;
  }
};

typedef struct _Collector_SendHeartbeat_args__isset {
  _Collector_SendHeartbeat_args__isset() : heartbeat_ad(false) {}
  bool heartbeat_ad;
} _Collector_SendHeartbeat_args__isset;

class Collector_SendHeartbeat_args {
 public:

  Collector_SendHeartbeat_args() : heartbeat_ad() {
  }

  virtual ~Collector_SendHeartbeat_args() throw() {}

  std::string heartbeat_ad;

  _Collector_SendHeartbeat_args__isset __isset;

  void __set_heartbeat_ad(const std::string& val) {
    heartbeat_ad = val;
  }

  bool operator == (const Collector_SendHeartbeat_args & rhs) const
  {
    if (!(heartbeat_ad == rhs.heartbeat_ad))
      return false;
    return true;
  }
  bool operator != (const Collector_SendHeartbeat_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_SendHeartbeat_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Collector_SendHeartbeat_pargs {
 public:


  virtual ~Collector_SendHeartbeat_pargs() throw() {}

  const std::string* heartbeat_ad;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Collector_SendHeartbeat_result {
 public:

  Collector_SendHeartbeat_result() {
  }

  virtual ~Collector_SendHeartbeat_result() throw() {}


  bool operator == (const Collector_SendHeartbeat_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Collector_SendHeartbeat_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_SendHeartbeat_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Collector_SendHeartbeat_presult {
 public:


  virtual ~Collector_SendHeartbeat_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Collector_RegistMachine_args__isset {
  _Collector_RegistMachine_args__isset() : machine_ad(false) {}
  bool machine_ad;
} _Collector_RegistMachine_args__isset;

class Collector_RegistMachine_args {
 public:

  Collector_RegistMachine_args() : machine_ad() {
  }

  virtual ~Collector_RegistMachine_args() throw() {}

  std::string machine_ad;

  _Collector_RegistMachine_args__isset __isset;

  void __set_machine_ad(const std::string& val) {
    machine_ad = val;
  }

  bool operator == (const Collector_RegistMachine_args & rhs) const
  {
    if (!(machine_ad == rhs.machine_ad))
      return false;
    return true;
  }
  bool operator != (const Collector_RegistMachine_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_RegistMachine_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Collector_RegistMachine_pargs {
 public:


  virtual ~Collector_RegistMachine_pargs() throw() {}

  const std::string* machine_ad;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Collector_RegistMachine_result__isset {
  _Collector_RegistMachine_result__isset() : success(false) {}
  bool success;
} _Collector_RegistMachine_result__isset;

class Collector_RegistMachine_result {
 public:

  Collector_RegistMachine_result() : success(0) {
  }

  virtual ~Collector_RegistMachine_result() throw() {}

  int32_t success;

  _Collector_RegistMachine_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Collector_RegistMachine_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Collector_RegistMachine_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_RegistMachine_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Collector_RegistMachine_presult__isset {
  _Collector_RegistMachine_presult__isset() : success(false) {}
  bool success;
} _Collector_RegistMachine_presult__isset;

class Collector_RegistMachine_presult {
 public:


  virtual ~Collector_RegistMachine_presult() throw() {}

  int32_t* success;

  _Collector_RegistMachine_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Collector_MatchMachine_args__isset {
  _Collector_MatchMachine_args__isset() : job_ad(false) {}
  bool job_ad;
} _Collector_MatchMachine_args__isset;

class Collector_MatchMachine_args {
 public:

  Collector_MatchMachine_args() : job_ad() {
  }

  virtual ~Collector_MatchMachine_args() throw() {}

  std::string job_ad;

  _Collector_MatchMachine_args__isset __isset;

  void __set_job_ad(const std::string& val) {
    job_ad = val;
  }

  bool operator == (const Collector_MatchMachine_args & rhs) const
  {
    if (!(job_ad == rhs.job_ad))
      return false;
    return true;
  }
  bool operator != (const Collector_MatchMachine_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_MatchMachine_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Collector_MatchMachine_pargs {
 public:


  virtual ~Collector_MatchMachine_pargs() throw() {}

  const std::string* job_ad;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Collector_MatchMachine_result__isset {
  _Collector_MatchMachine_result__isset() : success(false) {}
  bool success;
} _Collector_MatchMachine_result__isset;

class Collector_MatchMachine_result {
 public:

  Collector_MatchMachine_result() : success() {
  }

  virtual ~Collector_MatchMachine_result() throw() {}

  std::string success;

  _Collector_MatchMachine_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const Collector_MatchMachine_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Collector_MatchMachine_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_MatchMachine_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Collector_MatchMachine_presult__isset {
  _Collector_MatchMachine_presult__isset() : success(false) {}
  bool success;
} _Collector_MatchMachine_presult__isset;

class Collector_MatchMachine_presult {
 public:


  virtual ~Collector_MatchMachine_presult() throw() {}

  std::string* success;

  _Collector_MatchMachine_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Collector_QueryMachine_args__isset {
  _Collector_QueryMachine_args__isset() : machine(false) {}
  bool machine;
} _Collector_QueryMachine_args__isset;

class Collector_QueryMachine_args {
 public:

  Collector_QueryMachine_args() : machine() {
  }

  virtual ~Collector_QueryMachine_args() throw() {}

  std::string machine;

  _Collector_QueryMachine_args__isset __isset;

  void __set_machine(const std::string& val) {
    machine = val;
  }

  bool operator == (const Collector_QueryMachine_args & rhs) const
  {
    if (!(machine == rhs.machine))
      return false;
    return true;
  }
  bool operator != (const Collector_QueryMachine_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_QueryMachine_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Collector_QueryMachine_pargs {
 public:


  virtual ~Collector_QueryMachine_pargs() throw() {}

  const std::string* machine;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Collector_QueryMachine_result__isset {
  _Collector_QueryMachine_result__isset() : success(false) {}
  bool success;
} _Collector_QueryMachine_result__isset;

class Collector_QueryMachine_result {
 public:

  Collector_QueryMachine_result() : success() {
  }

  virtual ~Collector_QueryMachine_result() throw() {}

  std::string success;

  _Collector_QueryMachine_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const Collector_QueryMachine_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Collector_QueryMachine_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_QueryMachine_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Collector_QueryMachine_presult__isset {
  _Collector_QueryMachine_presult__isset() : success(false) {}
  bool success;
} _Collector_QueryMachine_presult__isset;

class Collector_QueryMachine_presult {
 public:


  virtual ~Collector_QueryMachine_presult() throw() {}

  std::string* success;

  _Collector_QueryMachine_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class Collector_ListAllMachines_args {
 public:

  Collector_ListAllMachines_args() {
  }

  virtual ~Collector_ListAllMachines_args() throw() {}


  bool operator == (const Collector_ListAllMachines_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Collector_ListAllMachines_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_ListAllMachines_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Collector_ListAllMachines_pargs {
 public:


  virtual ~Collector_ListAllMachines_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Collector_ListAllMachines_result__isset {
  _Collector_ListAllMachines_result__isset() : success(false) {}
  bool success;
} _Collector_ListAllMachines_result__isset;

class Collector_ListAllMachines_result {
 public:

  Collector_ListAllMachines_result() {
  }

  virtual ~Collector_ListAllMachines_result() throw() {}

  std::vector<std::string>  success;

  _Collector_ListAllMachines_result__isset __isset;

  void __set_success(const std::vector<std::string> & val) {
    success = val;
  }

  bool operator == (const Collector_ListAllMachines_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Collector_ListAllMachines_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Collector_ListAllMachines_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Collector_ListAllMachines_presult__isset {
  _Collector_ListAllMachines_presult__isset() : success(false) {}
  bool success;
} _Collector_ListAllMachines_presult__isset;

class Collector_ListAllMachines_presult {
 public:


  virtual ~Collector_ListAllMachines_presult() throw() {}

  std::vector<std::string> * success;

  _Collector_ListAllMachines_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class CollectorClient : virtual public CollectorIf {
 public:
  CollectorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  CollectorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void SendHeartbeat(const std::string& heartbeat_ad);
  void send_SendHeartbeat(const std::string& heartbeat_ad);
  void recv_SendHeartbeat();
  int32_t RegistMachine(const std::string& machine_ad);
  void send_RegistMachine(const std::string& machine_ad);
  int32_t recv_RegistMachine();
  void MatchMachine(std::string& _return, const std::string& job_ad);
  void send_MatchMachine(const std::string& job_ad);
  void recv_MatchMachine(std::string& _return);
  void QueryMachine(std::string& _return, const std::string& machine);
  void send_QueryMachine(const std::string& machine);
  void recv_QueryMachine(std::string& _return);
  void ListAllMachines(std::vector<std::string> & _return);
  void send_ListAllMachines();
  void recv_ListAllMachines(std::vector<std::string> & _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class CollectorProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<CollectorIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (CollectorProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_SendHeartbeat(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_RegistMachine(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_MatchMachine(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_QueryMachine(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ListAllMachines(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  CollectorProcessor(boost::shared_ptr<CollectorIf> iface) :
    iface_(iface) {
    processMap_["SendHeartbeat"] = &CollectorProcessor::process_SendHeartbeat;
    processMap_["RegistMachine"] = &CollectorProcessor::process_RegistMachine;
    processMap_["MatchMachine"] = &CollectorProcessor::process_MatchMachine;
    processMap_["QueryMachine"] = &CollectorProcessor::process_QueryMachine;
    processMap_["ListAllMachines"] = &CollectorProcessor::process_ListAllMachines;
  }

  virtual ~CollectorProcessor() {}
};

class CollectorProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  CollectorProcessorFactory(const ::boost::shared_ptr< CollectorIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< CollectorIfFactory > handlerFactory_;
};

class CollectorMultiface : virtual public CollectorIf {
 public:
  CollectorMultiface(std::vector<boost::shared_ptr<CollectorIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~CollectorMultiface() {}
 protected:
  std::vector<boost::shared_ptr<CollectorIf> > ifaces_;
  CollectorMultiface() {}
  void add(boost::shared_ptr<CollectorIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void SendHeartbeat(const std::string& heartbeat_ad) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->SendHeartbeat(heartbeat_ad);
    }
    ifaces_[i]->SendHeartbeat(heartbeat_ad);
  }

  int32_t RegistMachine(const std::string& machine_ad) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->RegistMachine(machine_ad);
    }
    return ifaces_[i]->RegistMachine(machine_ad);
  }

  void MatchMachine(std::string& _return, const std::string& job_ad) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->MatchMachine(_return, job_ad);
    }
    ifaces_[i]->MatchMachine(_return, job_ad);
    return;
  }

  void QueryMachine(std::string& _return, const std::string& machine) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->QueryMachine(_return, machine);
    }
    ifaces_[i]->QueryMachine(_return, machine);
    return;
  }

  void ListAllMachines(std::vector<std::string> & _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ListAllMachines(_return);
    }
    ifaces_[i]->ListAllMachines(_return);
    return;
  }

};



#endif
