/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Executor_H
#define Executor_H

#include <thrift/TDispatchProcessor.h>
#include "executor_types.h"



class ExecutorIf {
 public:
  virtual ~ExecutorIf() {}
  virtual int32_t Helloworld() = 0;
};

class ExecutorIfFactory {
 public:
  typedef ExecutorIf Handler;

  virtual ~ExecutorIfFactory() {}

  virtual ExecutorIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ExecutorIf* /* handler */) = 0;
};

class ExecutorIfSingletonFactory : virtual public ExecutorIfFactory {
 public:
  ExecutorIfSingletonFactory(const boost::shared_ptr<ExecutorIf>& iface) : iface_(iface) {}
  virtual ~ExecutorIfSingletonFactory() {}

  virtual ExecutorIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ExecutorIf* /* handler */) {}

 protected:
  boost::shared_ptr<ExecutorIf> iface_;
};

class ExecutorNull : virtual public ExecutorIf {
 public:
  virtual ~ExecutorNull() {}
  int32_t Helloworld() {
    int32_t _return = 0;
    return _return;
  }
};


class Executor_Helloworld_args {
 public:

  Executor_Helloworld_args() {
  }

  virtual ~Executor_Helloworld_args() throw() {}


  bool operator == (const Executor_Helloworld_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Executor_Helloworld_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Executor_Helloworld_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Executor_Helloworld_pargs {
 public:


  virtual ~Executor_Helloworld_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Executor_Helloworld_result__isset {
  _Executor_Helloworld_result__isset() : success(false) {}
  bool success;
} _Executor_Helloworld_result__isset;

class Executor_Helloworld_result {
 public:

  Executor_Helloworld_result() : success(0) {
  }

  virtual ~Executor_Helloworld_result() throw() {}

  int32_t success;

  _Executor_Helloworld_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Executor_Helloworld_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Executor_Helloworld_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Executor_Helloworld_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Executor_Helloworld_presult__isset {
  _Executor_Helloworld_presult__isset() : success(false) {}
  bool success;
} _Executor_Helloworld_presult__isset;

class Executor_Helloworld_presult {
 public:


  virtual ~Executor_Helloworld_presult() throw() {}

  int32_t* success;

  _Executor_Helloworld_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ExecutorClient : virtual public ExecutorIf {
 public:
  ExecutorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  ExecutorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t Helloworld();
  void send_Helloworld();
  int32_t recv_Helloworld();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ExecutorProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ExecutorIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ExecutorProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_Helloworld(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ExecutorProcessor(boost::shared_ptr<ExecutorIf> iface) :
    iface_(iface) {
    processMap_["Helloworld"] = &ExecutorProcessor::process_Helloworld;
  }

  virtual ~ExecutorProcessor() {}
};

class ExecutorProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ExecutorProcessorFactory(const ::boost::shared_ptr< ExecutorIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ExecutorIfFactory > handlerFactory_;
};

class ExecutorMultiface : virtual public ExecutorIf {
 public:
  ExecutorMultiface(std::vector<boost::shared_ptr<ExecutorIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ExecutorMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ExecutorIf> > ifaces_;
  ExecutorMultiface() {}
  void add(boost::shared_ptr<ExecutorIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t Helloworld() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Helloworld();
    }
    return ifaces_[i]->Helloworld();
  }

};



#endif
