/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef executor_CONSTANTS_H
#define executor_CONSTANTS_H

#include "executor_types.h"



class executorConstants {
 public:
  executorConstants();

};

extern const executorConstants g_executor_constants;



#endif
