// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Scheduler.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ;

class SchedulerHandler : virtual public SchedulerIf {
 public:
  SchedulerHandler() {
    // Your initialization goes here
  }

  int64_t SubmitJob(const std::string& job_ad) {
    // Your implementation goes here
    printf("SubmitJob\n");
  }

  bool ReportTaskState(const int64_t job_id, const int64_t task_id, const TaskState::type state) {
    // Your implementation goes here
    printf("ReportTaskState\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<SchedulerHandler> handler(new SchedulerHandler());
  shared_ptr<TProcessor> processor(new SchedulerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

