// default_xsl.h
#ifndef COMMON_BASELIB_SVRPUBLIB_DEFAULT_XSL_H_
#define COMMON_BASELIB_SVRPUBLIB_DEFAULT_XSL_H_

// default xsl
const char kDefaultXSL[] =
    "<?xml version=\"1.0\" encoding=\"utf-8\" ?>"
    "<xsl:stylesheet version=\"2.0\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\">"
    "<xsl:template match=\"/\">"
    "<html>\n"
    "<head>\n"
    "<link href='http://xfs.soso.oa.com/xfs/css/xfs_style.css' type='text/css' rel='stylesheet'/>"
    "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"></meta>"
    "<meta http-equiv=\"Content-Language\" content=\"zh-cn\"></meta>"
    "</head>\n"
    "<body>\n"
    "<!-- Set Module name -->"
    "<p>"
    "<i>Module : </i>"
    "<span class='module'><xsl:value-of select=\"Content/Module\"/>"
    "</span><br></br>"
    "<!-- Set Process -->"
    "Process:<xsl:value-of select=\"Content/Process\"/>"
    "</p>"
    "<!-- CPU -->"
    "<xsl:if test=\"Content/CPU != \'\'\">"
    "<table border=\"0\">"
    "<tr bgcolor=\"#9acd32\">"
    "<th align=\"left\">cpu</th>"
    "<th align=\"left\">desc</th>"
    "</tr>"
    "<xsl:choose>"
    "<xsl:when test=\"Content/CPU/Desc != \'\'\">"
    "<tr><td><font face=\"Verdana\">cpu</font></td>"
    "<td><xsl:value-of select=\"Content/CPU/Desc\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:when>"
    "<xsl:when test=\"Content/CPU/desc != \'\'\">"
    "<tr><td><font face=\"Verdana\">cpu</font></td>"
    "<td><xsl:value-of select=\"Content/CPU/desc\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:when>"
    "</xsl:choose>"
    "<xsl:for-each select=\"Content/CPU/*[position()>1]\">"
    "<tr><td><font face=\"Verdana\"><xsl:value-of select=\"name()\"/></font></td>"
    "<td><xsl:value-of select=\".\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!-- Mem -->"
    "<xsl:if test=\"Content/MEM != \'\'\">"
    "<table border=\"0\">"
    "<tr bgcolor=\"#9acd32\">"
    "<th align=\"left\">Memory</th>"
    "<th align=\"left\" colspan=\"6\">desc</th>"
    "</tr>"
    "<xsl:choose>"
    "<xsl:when test=\"Content/MEM/Desc != \'\'\">"
    "<tr><td><font face=\"Verdana\">Mem</font></td>"
    "<td><xsl:value-of select=\"Content/MEM/Desc\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:when>"
    "<xsl:when test=\"Content/MEM/desc != \'\'\">"
    "<tr><td><font face=\"Verdana\">Mem</font></td>"
    "<td><xsl:value-of select=\"Content/MEM/desc\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:when>"
    "</xsl:choose>"
    "<xsl:if test=\"Content/MEM/SystemMemory != \'\'\">"
    "<xsl:for-each select=\"Content/MEM/SystemMemory\">"
    "<tr bgcolor=\"#99cccc\"><td><font face=\"Verdana\">SystemMemory</font></td>"
    "<td>MemTotal</td><td>MemFree</td><td>Buffers</td>"
    "<td>SwapTotal</td><td>SwapFree</td><td>Cached</td></tr>"
    "<tr><td></td><td><xsl:value-of select=\"MemTotal\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"MemFree\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Buffers\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"SwapTotal\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"SwapFree\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Cached\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:for-each>"
    "</xsl:if>"
    "<xsl:if test=\"Content/MEM/ProcessMemory != \'\'\">"
    "<xsl:for-each select=\"Content/MEM/ProcessMemory\">"
    "<tr bgcolor=\"#99cccc\"><td><font face=\"Verdana\">ProcessMemory</font></td>"
    "<td>Pid</td><td>FDSize</td><td>VmSize</td><td>VmRSS</td>"
    "<td>VmData</td><td>VmLib</td></tr>"
    "<tr><td></td><td><xsl:value-of select=\"Pid\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"FDSize\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"VmSize\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"VmRSS\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"VmData\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"VmLib\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:for-each>"
    "</xsl:if>"
    "<xsl:if test=\"Content/MEM/ThreadMemory != \'\'\">"
    "<tr bgcolor=\"#99cccc\"><td><font face=\"Verdana\">ThreadMemory</font></td>"
    "<td>Threadid</td><td>FDSize</td><td>VmSize</td><td>VmRSS</td>"
    "<td>VmData</td><td>VmLib</td></tr>"
    "<xsl:for-each select=\"Content/MEM/ThreadMemory\">"
    "<xsl:if test=\"(position() mod 2) = 1\">"
    "<tr><td></td><td><xsl:value-of select=\"ThreadId\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"FDSize\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"VmSize\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"VmRSS\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"VmData\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"VmLib\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:if>"
    "<xsl:if test=\"(position() mod 2) = 0\">"
    "<tr bgcolor=\"#ccffcc\"><td bgcolor=\"#ffffff\"></td>"
    "<td><xsl:value-of select=\"ThreadId\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"FDSize\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"VmSize\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"VmRSS\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"VmData\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"VmLib\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:if>"
    "</xsl:for-each>"
    "</xsl:if>"
    "</table>"
    "</xsl:if>"
    "<!-- Disk -->"
    "<xsl:if test=\"Content/DISK != \'\'\">"
    "<table border=\"0\">"
    "<tr bgcolor=\"#9acd32s\">"
    "<th align=\"left\">Disk</th>"
    "<th align=\"left\">desc/autokey</th>"
    "</tr>"
    "<xsl:choose>"
    "<xsl:when test=\"Content/DISK/Desc != \'\'\">"
    "<tr><td><font face=\"Verdana\">Disk</font></td>"
    "<td><xsl:value-of select=\"Content/DISK/Desc\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:when>"
    "<xsl:when test=\"Content/DISK/desc != \'\'\">"
    "<tr><td><font face=\"Verdana\">Disk</font></td>"
    "<td><xsl:value-of select=\"Content/DISK/desc\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:when>"
    "<xsl:when test=\"Content/DISK/autokey != \'\'\">"
    "<tr><td><font face=\"Verdana\">autokey</font></td>"
    "<td><font face=\"Courier New\">"
    "<xsl:value-of select=\"Content/DISK/autokey\" disable-output-escaping=\"yes\"/></font></td></tr>"
    "</xsl:when>"
    "</xsl:choose>"
    "</table>"
    "</xsl:if>"
    "<!-- Net -->"
    "<xsl:if test=\"Content/NET != \'\'\">"
    "<table border=\"0\">"
    "<tr bgcolor=\"#9acd32s\">"
    "<th align=\"left\">Net</th>"
    "<th align=\"left\">desc</th>"
    "</tr>"
    "<xsl:choose>"
    "<xsl:when test=\"Content/NET/Desc != \'\'\">"
    "<tr><td><font face=\"Verdana\">Net</font></td>"
    "<td><xsl:value-of select=\"Content/NET/Desc\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:when>"
    "<xsl:when test=\"Content/NET/desc != \'\'\">"
    "<tr><td><font face=\"Verdana\">Net</font></td>"
    "<td><xsl:value-of select=\"Content/NET/desc\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:when>"
    "<xsl:when test=\"Content/NET/autokey != \'\'\">"
    "<xsl:for-each select=\"Content/NET/autokey\">"
    "<tr><td><font face=\"Verdana\">autokey</font></td>"
    "<td><font face=\"Courier New\">"
    "<xsl:value-of select=\".\" disable-output-escaping=\"yes\"/></font></td></tr>"
    "</xsl:for-each>"
    "</xsl:when>"
    "</xsl:choose>"
    "</table>"
    "</xsl:if>"
    "<!-- Help -->"
    "<xsl:if test=\"Content/Help != \'\'\">"
    "<table border=\"0\">"
    "<tr bgcolor=\"#9acd32\">"
    "<th align=\"left\">Help</th>"
    "<th align=\"left\">help-xml</th>"
    "<th align=\"left\">home</th>"
    "</tr>"
    "<tr>"
    "<td></td><td><xsl:value-of select=\"Content/Help/help-xml\"/></td>"
    "<td><xsl:value-of select=\"Content/Help/home\" disable-output-escaping=\"yes\"/></td>"
    "</tr>"
    "</table>"
    "</xsl:if>"
    "<!-- AutoKey -->"
    "<xsl:if test=\"Content/autokey != \'\'\">"
    "<table border=\"0\">"
    "<tr bgcolor=\"#9acd32\"><td><font face=\"Verdana\">autokey</font></td><td>desc</td></tr>"
    "<xsl:for-each select=\"Content/autokey\">"
    "<tr><td></td><td><xsl:value-of select=\".\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!--  ****** scheduler_master  *********  -->"
    "<!-- recycle_file -->"
    "<xsl:if test=\"Content/recycle_file != \'\'\">"
    "<table border=\"0\">"
    "<tr bgcolor=\"#9acd32\"><td><font face=\"Verdana\">"
    "<xsl:value-of select=\"Content/recycle_file\" disable-output-escaping=\"yes\"/>"
    "</font></td><td>files</td></tr>"
    "<xsl:for-each select=\"Content/file\">"
    "<tr><td></td><td><xsl:value-of select=\".\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!-- free_space -->"
    "<xsl:if test=\"Content/xfs_cluster_info/XFSTotalNodeNum != \'\'\">"
    "<table border=\"0\"  cellpadding=\"10\">"
    "<tr bgcolor=\"#9acd32\"><td><font face=\"Verdana\">TotalNodeServer:</font></td><td colspan=\"7\">"
    "<xsl:value-of select=\"Content/TotalNodeServer\" disable-output-escaping=\"yes\"/></td></tr>"
    "<tr bgcolor=\"#99cccc\"><td>Ip</td><td>Version</td><td>TotalNode</td>"
    "<td>FreeNode</td><td>UsedNode</td><td>TotalSpace</td><td>FreeSpace</td><td>UsedSpace</td></tr>"
    "<xsl:for-each select=\'Content/nodeserver\'>"
    "<xsl:if test=\'(position() mod 2) = 0\'>"
    "<tr bgcolor=\'#ccffcc\'>"
    "<td><xsl:value-of select=\'Ip\' disable-output-escaping=\'yes\'/></td>"
    "<td><xsl:value-of select=\'Version\' disable-output-escaping=\'yes\'/></td>"
    "<td><xsl:value-of select=\'TotalNode\' disable-output-escaping=\'yes\'/></td>"
    "<td><xsl:value-of select=\'FreeNode\' disable-output-escaping=\'yes\'/></td>"
    "<td><xsl:value-of select=\'UsedNode\' disable-output-escaping=\'yes\'/></td>"
    "<td><xsl:value-of select=\"TotalSpace\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"FreeSpace\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"UsedSpace\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:if>"
    "<xsl:if test=\"(position() mod 2) = 1\">"
    "<tr><td><xsl:value-of select=\'Ip\' disable-output-escaping=\'yes\'/></td>"
    "<td><xsl:value-of select=\'Version\' disable-output-escaping=\'yes\'/></td>"
    "<td><xsl:value-of select=\'TotalNode\' disable-output-escaping=\'yes\'/></td>"
    "<td><xsl:value-of select=\'FreeNode\' disable-output-escaping=\'yes\'/></td>"
    "<td><xsl:value-of select=\'UsedNode\' disable-output-escaping=\'yes\'/></td>"
    "<td><xsl:value-of select=\"TotalSpace\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"FreeSpace\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"UsedSpace\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:if>"
    "</xsl:for-each>"
    "<tr><td>Sum</td><td></td>"
    "<td><xsl:value-of select=\'Content/xfs_cluster_info/XFSTotalNodeNum\'"
    " disable-output-escaping=\'yes\'/></td>"
    "<td><xsl:value-of select=\'Content/xfs_cluster_info/XFSFreeNodeNum\'"
    " disable-output-escaping=\'yes\'/></td>"
    "<td><xsl:value-of select=\'Content/xfs_cluster_info/XFSUsedNodeNum\'"
    " disable-output-escaping=\'yes\'/></td>"
    "<td><xsl:value-of select=\"Content/xfs_cluster_info/XFSTotalSpace\""
    " disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Content/xfs_cluster_info/XFSFreeSpace\""
    " disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Content/xfs_cluster_info/XFSUsedSpace\""
    " disable-output-escaping=\"yes\"/></td></tr>"
    "</table>"
    "</xsl:if>"
    "<xsl:if test=\"Content/error|Content/Error != \'\'\">"
    "<table border=\"0\" cellpadding=\"10\">"
    "<tr bgcolor=\"#9acd32\"><td><font face=\"Verdana\">error</font></td><td>desc</td></tr>"
    "<xsl:for-each select=\"Content/error|Content/Error\">"
    "<tr><td></td><td><xsl:value-of select=\".\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<xsl:if test=\"Content/group_0\">"
    "<table border=\"0\"  cellpadding=\"10\">"
    "<tr bgcolor=\"#9acd32\"><td>Ip</td><td>LocalId</td><td>Time</td>"
    "<xsl:if test='Content/group_0/FileNo'><td>FileNo</td><td>FileId</td></xsl:if></tr>"
    "<xsl:for-each select='Content/*'>"
    "<xsl:if test=\"(position() mod 2) = 0\">"
    "<tr bgcolor=\"#ccffcc\"><td><xsl:value-of select=\"Ip\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"LocalId\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Time\" disable-output-escaping=\"yes\"/></td>"
    "<xsl:if test=\"Content/group_0/FileNo\"><td>"
    "<xsl:value-of select=\"FileNo\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"FileId\" disable-output-escaping=\"yes\"/></td></xsl:if></tr>"
    "</xsl:if>"
    "<xsl:if test=\"(position() mod 2) = 1\">"
    "<tr><td><xsl:value-of select=\"Ip\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"LocalId\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Time\" disable-output-escaping=\"yes\"/></td>"
    "<xsl:if test=\"Content/group_0/FileNo\"><td>"
    "<xsl:value-of select=\"FileNo\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"FileId\" disable-output-escaping=\"yes\"/></td></xsl:if></tr>"
    "</xsl:if>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!--  ******** node_server  **********  -->"
    "<!-- free_node -->"
    "<xsl:if test=\"Content/free_node != \'\'\">"
    "<table border=\"0\">"
    "<tr bgcolor=\"#99cccc\"><td><font face=\"Verdana\">"
    "TotalNode:<xsl:value-of select=\"Content/total_node\" disable-output-escaping=\"yes\"/>"
    "</font></td><td><font face=\"Verdana\">FreeNode:"
    "<xsl:value-of select=\"Content/free_node\" disable-output-escaping=\"yes\"/></font></td></tr>"
    "<tr bgcolor=\"#99cccc\"><td><font face=\"Verdana\">LocalId</font></td></tr>"
    "<xsl:for-each select=\"Content/local_id\">"
    "<xsl:if test=\"(position() mod 2) = 1\">"
    "<tr><td><xsl:value-of select=\".\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:if>"
    "<xsl:if test=\"(position() mod 2) = 0\">"
    "<tr bgcolor=\"#ccffcc\"><td><xsl:value-of select=\".\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:if>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!-- show_flow -->"
    "<xsl:if test=\"Content/nodesvr_flow_item != \'\'\">"
    "<table border=\"0\">"
    "<tr bgcolor=\"#99cccc\"><td>hour</td><td>seek</td><td>inflow</td><td>outflow</td></tr>"
    "<xsl:for-each select=\"Content/nodesvr_flow_item\">"
    "<xsl:if test=\"(position() mod 2) = 0\">"
    "<tr bgcolor=\"#ccffcc\">"
    "<td><xsl:value-of select=\"hour\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"seek\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"inflow\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"outflow\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:if>"
    "<xsl:if test=\"(position() mod 2) = 1\">"
    "<tr><td><xsl:value-of select=\"hour\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"seek\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"inflow\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"outflow\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:if>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!-- show_used_node(undo) -->"
    "<!--  ********  scheduler_client  ********  -->"
    "<!-- stat -->"
    "<xsl:if test=\"Content/ScanOrphanNodesResult != \'\'\">"
    "<table border=\"0\" cellpadding=\"10\">"
    "<tr bgcolor=\"#99cccc\"><td><font face=\"Verdana\">ScanType</font></td>"
    "<td><font face=\"Verdana\">BeginTime</font></td>"
    "<td><font face=\"Verdana\">EndTime</font></td>"
    "<td><font face=\"Verdana\">ScanResult</font></td>"
    "<td><font face=\"Verdana\">ErrListLink</font></td></tr>"
    "<xsl:for-each select=\"Content/*\">"
    "<tr><td><xsl:value-of select=\"*[1]\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Start_scan_time\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Stop_scan_time\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"*[4]\" disable-output-escaping=\"yes\"/></td>"
    "<td><a><xsl:attribute name=\"href\"><xsl:value-of select=\"*[5]/Url\"/>"
    "</xsl:attribute><xsl:value-of select=\"*[5]/Title\" disable-output-escaping=\"yes\"/></a></td></tr>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!-- HashErrorList ErrorNodeList OrphanList-->"
    "<xsl:if test=\"Content/HashErrorList != \'\' or"
    " Content/ErrorNodeList != \'\' or Content/OrphanList != \'\'\">"
    "<table border=\"0\" cellpadding=\"10\">"
    "<tr bgcolor=\"#99cccc\"><td><font face=\"Verdana\">"
    "<xsl:value-of select=\"Content/HashErrorList/*[1]\" disable-output-escaping=\"yes\"/></font></td></tr>"
    "<xsl:for-each select=\"Content/HashErrorList/*[position()>1]"
    " | Content/ErrorNodeList/*[position()>1] | Content/OrphanList/*[position()>1]\">"
    "<tr><td><xsl:value-of select=\"name()\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\".\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!--  ************ meta_server  *********  -->"
    "<!-- stat -->"
    "<xsl:if test=\"Content/LOG_MSG != \'\'\">"
    "<table border=\"0\" cellpadding=\"10\">"
    "<tr bgcolor=\"#99cccc\"><td><font face=\"Verdana\">ScanType</font></td>"
    "<td><font face=\"Verdana\">BeginTime</font></td><td><font face=\"Verdana\">EndTime</font></td>"
    "<td><font face=\"Verdana\">ScanResult</font></td><td><font face=\"Verdana\">ErrListLink</font></td></tr>"
    "<xsl:for-each select=\"Content/LOG_MSG/*\">"
    "<tr><td><xsl:value-of select=\"name()\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\".\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!-- localblocklist -->"
    "<xsl:if test=\"Content/LocalBlockList != \'\'\">"
    "<table border=\"0\" cellpadding=\"10\">"
    "<tr bgcolor=\"#99cccc\"><td></td><td>LocalBlockList</td></tr>"
    "<xsl:for-each select=\"Content/LocalBlockList/*\">"
    "<tr><td><xsl:value-of select=\"name()\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\".\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!-- QueryFileMeta -->"
    "<xsl:if test=\"Content/QueryFileMeta != \'\'\">"
    "<table border=\"0\" cellpadding=\"10\">"
    "<tr bgcolor=\"#99cccc\"><td>FileId</td><td>Desc</td></tr>"
    "<xsl:for-each select=\"Content/QueryFileMeta/FileId\">"
    "<tr><td><xsl:value-of select=\".\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"@desc\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!--  ********  master  ************  -->"
    "<!-- filelist -->"
    "<xsl:if test=\"Content/Directory_of != \'\'\">"
    "<div>Directory_of : <xsl:value-of select=\"Content/Directory_of\" disable-output-escaping=\"yes\"/></div>"
    "<table border=\"0\">"
    "<tr bgcolor=\"#99cccc\"><td>FileName</td>"
    "<td>FileId</td><td>CreateUser</td><td>ModifyUser</td><td>CreateTime</td>"
    "<td>NumChunks</td><td>NumBackups</td></tr>"
    "<xsl:for-each select=\"Content/dir\">"
    "<tr><td><a><xsl:attribute name=\"href\"><xsl:value-of select=\"Link/Url\"/>"
    "</xsl:attribute><xsl:value-of select=\"DirName\" disable-output-escaping=\"yes\"/></a></td>"
    "<td></td><td>"
    "<xsl:value-of select=\"CreateUser\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"ModifyUser\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"CreateTime\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:for-each>"
    "<xsl:for-each select=\"Content/file\">"
    "<xsl:if test=\"(position() mod 2) = 1\">"
    "<tr><td><xsl:value-of select=\"FileName\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"FileId\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"CreateUser\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"ModifyUser\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"CreateTime\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"NumChunks\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"NumBackups\" disable-output-escaping=\"yes\"/></td>"
    "</tr></xsl:if>"
    "<xsl:if test=\"(position() mod 2) = 0\">"
    "<tr bgcolor=\"#ccffcc\"><td><xsl:value-of select=\"FileName\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"FileId\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"CreateUser\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"ModifyUser\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"CreateTime\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"NumChunks\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"NumBackups\" disable-output-escaping=\"yes\"/></td>"
    "</tr></xsl:if>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!-- MasterReplication -->"
    "<xsl:if test=\"Content/Replication != \'\'\">"
    "<table border=\"0\" cellpadding=\"10\">"
    "<xsl:for-each select=\"Content/Replication/*\">"
    "<tr><td><xsl:value-of select=\"name()\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\".\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"@desc\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!-- ListMasterFiles -->"
    "<xsl:if test=\"Content/MasterFile != \'\'\">"
    "<table border=\"0\">"
    "<tr bgcolor=\"#99cccc\"><td>FileName</td><td>BeginSequenceID</td>"
    "<td>EndSequenceID</td><td>CreateTime</td><td>IsSealed</td><td>Type</td></tr>"
    "<xsl:for-each select=\"Content/MasterFile\">"
    "<xsl:if test=\"(position() mod 2) = 1\">"
    "<tr><td><xsl:value-of select=\"FileName\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"BeginSequenceID\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"EndSequenceID\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"CreateTime\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"IsSealed\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Type\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:if>"
    "<xsl:if test=\"(position() mod 2) = 0\">"
    "<tr bgcolor=\"#ccffcc\"><td><xsl:value-of select=\"FileName\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"BeginSequenceID\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"EndSequenceID\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"CreateTime\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"IsSealed\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Type\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:if>"
    "</xsl:for-each>"
    "</table>"
    "</xsl:if>"
    "<!-- master_quotas -->"
    "<xsl:if test=\"Content/Role != \'\'\">"
    "<table border=\"0\">"
    "<tr bgcolor=\"#99cccc\"><td></td>"
    "<td>Role</td><td>FilesUsed</td><td>DirsUsed</td><td>ChunksUsed</td>"
    "<td>FilesQuota</td><td>DirsQuota</td><td>ChunksQuota</td></tr>"
    "<xsl:for-each select=\"Content/Role\">"
    "<xsl:if test=\"(position() mod 2) = 0\">"
    "<tr bgcolor=\"#ccffcc\"><td></td>"
    "<td><xsl:value-of select=\"RoleName\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"FilesUsed\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"DirsUsed\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"ChunksUsed\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"FilesQuota\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"DirsQuota\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"ChunksQuota\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:if>"
    "<xsl:if test=\"(position() mod 2) = 1\">"
    "<tr><td></td><td><xsl:value-of select=\"RoleName\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"FilesUsed\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"DirsUsed\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"ChunksUsed\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"FilesQuota\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"DirsQuota\" disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"ChunksQuota\" disable-output-escaping=\"yes\"/></td></tr>"
    "</xsl:if>"
    "</xsl:for-each>"
    "<tr bgcolor=\"#99cccc\"><td>Total</td>"
    "<td><xsl:value-of select=\"Content/TotalRoles/TotalNumRoles\""
    " disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Content/TotalRoles/TotalFilesUsed\""
    " disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Content/TotalRoles/TotalDirsUsed\""
    " disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Content/TotalRoles/TotalChunksUsed\""
    " disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Content/TotalRoles/TotalFilesQuota\""
    " disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Content/TotalRoles/TotalDirsQuota\""
    " disable-output-escaping=\"yes\"/></td>"
    "<td><xsl:value-of select=\"Content/TotalRoles/TotalChunksQuota\""
    " disable-output-escaping=\"yes\"/></td></tr>"
    "</table>"
    "</xsl:if>"
    "<!-- Bottom -->"
    "<table border=\"0\">"
    "<tr bgcolor=\"#9acd32\">"
    "<th align=\"left\">links</th>"
    "<th align=\"left\">desc</th>"
    "</tr>"
    "<xsl:for-each select=\"Content/Link | Content/LogLink/Link\">"
    "<tr>"
    "<td><font face=\"Verdana\"><a><xsl:attribute name=\"href\"><xsl:value-of select=\"Url\"/>"
    "</xsl:attribute> <xsl:value-of select=\"Title\"/></a></font></td>"
    "<td><xsl:value-of select=\"Desc\"/></td>"
    "</tr> </xsl:for-each>"
    "</table>"
    "</body></html></xsl:template>"
    "</xsl:stylesheet>";

#endif // COMMON_BASELIB_SVRPUBLIB_DEFAULT_XSL_H_

