// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/net/poppy/rpc_option.proto

#ifndef PROTOBUF_common_2fnet_2fpoppy_2frpc_5foption_2eproto__INCLUDED
#define PROTOBUF_common_2fnet_2fpoppy_2frpc_5foption_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

namespace poppy {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_common_2fnet_2fpoppy_2frpc_5foption_2eproto();
void protobuf_AssignDesc_common_2fnet_2fpoppy_2frpc_5foption_2eproto();
void protobuf_ShutdownFile_common_2fnet_2fpoppy_2frpc_5foption_2eproto();


// ===================================================================


// ===================================================================

static const int kServiceTimeoutFieldNumber = 20000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int64 >, 3, false >
  service_timeout;
static const int kMethodTimeoutFieldNumber = 20000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int64 >, 3, false >
  method_timeout;

// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace poppy

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2fnet_2fpoppy_2frpc_5foption_2eproto__INCLUDED
